export const blogItems = [
  {
    id: "number-1",
    num: "1",
    title: "Proin vitae odio pharetra, sollicitudin est quis, imperdiet elit",
    category: "Music",
    category_path: "Music",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
    banner: "/public_assets/img/rand1.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
  },
  {
    id: "number-2",
    num: "2",
    title: "Etiam interdum metus malesuada, pulvinar lorem id, tristique purus",
    category: "Music",
    category_path: "music",
    banner: "/public_assets/img/rand2.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-3",
    num: "3",
    title: "Sed non arcu congue magna euismod ornare vel nec libero",
    category: "Sports",
    category_path: "sports",
    banner: "/public_assets/img/rand3.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-4",
    num: "4",
    title: "In mollis ex commodo, posuere felis vel, luctus metus",
    category: "Sports",
    category_path: "sports",
    banner: "/public_assets/img/rand4.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-5",
    num: "5",
    title: "Donec eu sem imperdiet, molestie mauris nec, dictum mauris",
    category: "Entertainment",
    category_path: "entertainment",
    banner: "/public_assets/img/rand5.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-6",
    num: "6",
    title: "Integer congue enim a lorem tincidunt, quis pharetra sem vehicula",
    category: "Culture",
    category_path: "culture",
    banner: "/public_assets/img/rand6.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-7",
    num: "7",
    title: "Sed faucibus lectus a quam viverra, a vulputate ipsum iaculis",
    category: "Culture",
    category_path: "culture",
    banner: "/public_assets/img/rand7.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-8",
    num: "8",
    title: "Integer vel dolor ac eros aliquam ultricies eu pulvinar nunc",
    category: "News",
    category_path: "news",
    banner: "/public_assets/img/rand8.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-9",
    num: "9",
    title: "Duis mollis dui viverra, pretium risus eu, ullamcorper metus",
    category: "News",
    category_path: "news",
    banner: "/public_assets/img/rand9.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-10",
    num: "10",
    title: "Aenean vitae odio vitae lorem pulvinar feugiat ac quis lorem",
    category: "News",
    category_path: "news",
    banner: "/public_assets/img/rand10.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-11",
    num: "11",
    title: "Phasellus rhoncus arcu sit amet felis condimentum commodo",
    category: "News",
    category_path: "news",
    banner: "/public_assets/img/rand11.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-12",
    num: "12",
    title: "Cras vitae tellus in felis mattis vulputate ut vel ipsum",
    category: "Entertainment",
    category_path: "entertainment",
    banner: "/public_assets/img/rand12.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
];
