export const blogItems = [
  {
    id: "number-1",
    num: "1",
    title: "Seven Shocking Facts About Music",
    category: "Música",
    category_path: "musica",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
    banner: "/public_assets/img/rand1.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
  },
  {
    id: "number-2",
    num: "2",
    title: "Ten Ingenious Ways You Can Do With Music",
    category: "Música",
    category_path: "musica",
    banner: "/public_assets/img/rand2.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-3",
    num: "3",
    title: "5 Things Everyone Gets Wrong About Sport",
    category: "Deportes",
    category_path: "deportes",
    banner: "/public_assets/img/rand3.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-4",
    num: "4",
    title: "10 Things You Learned in Preschool That'll Help You With Sport",
    category: "Deportes",
    category_path: "deportes",
    banner: "/public_assets/img/rand4.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-5",
    num: "5",
    title: "15 Weird Hobbies That'll Make You Better at Entertainment",
    category: "Entretenimiento",
    category_path: "entretenimiento",
    banner: "/public_assets/img/rand5.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-6",
    num: "6",
    title: "30 Inspirational Quotes About Entertainment",
    category: "Otros",
    category_path: "otros",
    banner: "/public_assets/img/rand6.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-7",
    num: "7",
    title: "Title 7",
    category: "Otros",
    category_path: "otros",
    banner: "/public_assets/img/rand7.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-8",
    num: "8",
    title: "Title 8",
    category: "Noticias",
    category_path: "noticias",
    banner: "/public_assets/img/rand8.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-9",
    num: "9",
    title: "Title 9",
    category: "Noticias",
    category_path: "noticias",
    banner: "/public_assets/img/rand9.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-10",
    num: "10",
    title: "Title 10",
    category: "Noticias",
    category_path: "noticias",
    banner: "/public_assets/img/rand10.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-11",
    num: "11",
    title: "Title 11",
    category: "Noticias",
    category_path: "noticias",
    banner: "/public_assets/img/rand11.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
  {
    id: "number-12",
    num: "12",
    title: "Title 12",
    category: "Noticias",
    category_path: "noticias",
    banner: "/public_assets/img/rand12.jpg",
    author: "John Doe",
    date: "Jul 11, 2022",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, veritatis saepe. Quia vero, optio odit debitis dolorem eveniet voluptatibus a.",
  },
];
